AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile

Style/Documentation:
  Enabled: false
